name: Push-to-EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSH key
      run: ssh-keygen -t rsa -b 4096 -f $HOME/.ssh/id_rsa -N ""

    - name: Copy SSH key to remote server
      uses: appleboy/scp-action@master
      with:
        host: 52.55.149.203
        username: ubuntu
        password: redhat
        source: $HOME/.ssh/id_rsa.pub
        target: /home/ubuntu/.ssh/authorized_keys

    - name: Run SSH command
      uses: appleboy/ssh-action@master
      with:
        host: 52.55.149.203
        username: ubuntu
        key: $HOME/.ssh/id_rsa
        script: |
          sudo apt-get -y update
          sudo apt-get install -y apache2
          sudo systemctl start apache2
          sudo systemctl enable apache2
          cd /home
          sudo mv * /var/www/html
        timeout: 30s
        command_timeout: 10m
        proxy_port: 22
        proxy_timeout: 30s
